doctrine:
    dbal:
        driver: pdo_pgsql
        dbname: '%env(resolve:POSTGRES_DB)%'
        host: '%env(resolve:POSTGRES_HOST)%'
        port: '%env(resolve:POSTGRES_PORT)%'
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        charset: UTF8
        server_version: 12

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            custom_mapping:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/app/DoctrineORM/'
                prefix: TodoCore\Domain\Entity
                alias: TodoCode